import {
  PhArrowsClockwise,
  PhArrowsDownUp,
  PhArrowsLeftRight,
  PhAtom,
  PhBank,
  PhBookOpen,
  PhBookOpenText,
  PhBookmarkSimple,
  PhBooks,
  PhBuildings,
  PhCalculator,
  PhChartBar,
  PhChartLineDown,
  PhChartLineUp,
  PhChartPie,
  PhChatTeardrop,
  PhClipboardText,
  PhCraneTower,
  PhDiceFive,
  PhDna,
  PhFire,
  PhFlask,
  PhFolderOpen,
  PhFolders,
  PhGear,
  PhGlobe,
  PhGlobeHemisphereEast,
  PhGraph,
  PhHeart,
  PhHourglassHigh,
  PhHouse,
  PhHouseSimple,
  PhInfo,
  PhKeyboard,
  PhLightbulb,
  PhLink,
  PhLockSimple,
  PhMagnifyingGlass,
  PhMapPin,
  PhMapTrifold,
  PhMicrophoneStage,
  PhMicroscope,
  PhMusicNotes,
  PhMusicNotesSimple,
  PhNotePencil,
  PhPalette,
  PhPaperclip,
  PhPencilSimple,
  PhPuzzlePiece,
  PhRobot,
  PhRuler,
  PhScroll,
  PhShieldCheck,
  PhListBullets,
  PhSquaresFour,
  PhSpeakerHigh,
  PhStar,
  PhTagSimple,
  PhTarget,
  PhTent,
  PhTextAa,
  PhToolbox,
  PhTreeStructure,
  PhWaves,
  PhWrench,
} from '@phosphor-icons/vue'

export const PHOSPHOR_MAP = {
  '⚛️': PhAtom,
  '⚙️': PhGear,
  '✏️': PhPencilSimple,
  '❤️': PhHeart,
  '⭐': PhStar,
  '🆚': PhArrowsDownUp,
  '🌊': PhWaves,
  '🌍': PhGlobeHemisphereEast,
  '🌐': PhInfo,
  '🌳': PhTreeStructure,
  '🎙️': PhMicrophoneStage,
  '🎨': PhPalette,
  '🎯': PhTarget,
  '🎲': PhDiceFive,
  '🎵': PhMusicNotes,
  '🎼': PhMusicNotesSimple,
  '🏕️': PhTent,
  '🏗️': PhCraneTower,
  '🏘️': PhBuildings,
  '🏛️': PhBank,
  '🏠': PhHouse,
  '🏡': PhHouseSimple,
  '🏷️': PhTagSimple,
  '🏺': PhHourglassHigh,
  '💡': PhLightbulb,
  '💬': PhChatTeardrop,
  '📂': PhFolderOpen,
  '📈': PhChartLineUp,
  '📉': PhChartLineDown,
  '📊': PhChartBar,
  '📋': PhClipboardText,
  '📍': PhMapPin,
  '📎': PhPaperclip,
  '📐': PhRuler,
  '📖': PhBookOpenText,
  '📗': PhBookOpen,
  '📚': PhListBullets,
  '📜': PhScroll,
  '📝': PhNotePencil,
  '🔄': PhArrowsClockwise,
  '🔍': PhMagnifyingGlass,
  '🔒': PhLockSimple,
  '🔖': PhBookmarkSimple,
  '🔗': PhLink,
  '🔣': PhKeyboard,
  '🔤': PhTextAa,
  '🔥': PhFire,
  '🔬': PhMicroscope,
  '🕸️': PhGraph,
  '🗂️': PhFolders,
  '🗣️': PhSpeakerHigh,
  '🗺️': PhMapTrifold,
  '🛠️': PhWrench,
  '🛡️': PhShieldCheck,
  '🤖': PhRobot,
  '🥧': PhChartPie,
  '🧩': PhPuzzlePiece,
  '🧪': PhFlask,
  '🧬': PhDna,
  '🧮': PhCalculator,
  '🧰': PhToolbox,
  '↔️': PhArrowsLeftRight,
  'ℹ️': PhInfo,
}

export function resolvePhosphorIcon(icon) {
  return PHOSPHOR_MAP[icon] || null
}
