import {
  PhArrowDown,
  PhArrowsClockwise,
  PhArrowsDownUp,
  PhArrowsLeftRight,
  PhArrowsOut,
  PhArrowsIn,
  PhAtom,
  PhBank,
  PhBookOpen,
  PhBookOpenText,
  PhBookmarkSimple,
  PhBooks,
  PhBuildings,
  PhCalculator,
  PhCalendar,
  PhChartBar,
  PhChartLineDown,
  PhChartLineUp,
  PhChartPie,
  PhChatTeardrop,
  PhCheck,
  PhCheckCircle,
  PhCheckFat,
  PhCheckSquare,
  PhCircle,
  PhClipboardText,
  PhCompass,
  PhConfetti,
  PhCraneTower,
  PhDesktop,
  PhDiamond,
  PhDiceFive,
  PhDna,
  PhDoor,
  PhDrop,
  PhEnvelope,
  PhFile,
  PhFire,
  PhFlask,
  PhFloppyDisk,
  PhFolder,
  PhFolderOpen,
  PhFolders,
  PhGear,
  PhGift,
  PhGlobe,
  PhGlobeHemisphereEast,
  PhGraph,
  PhHandPointing,
  PhHandsPraying,
  PhHeart,
  PhHexagon,
  PhHourglassHigh,
  PhHouse,
  PhHouseSimple,
  PhImage,
  PhInfo,
  PhKeyboard,
  PhLightbulb,
  PhLightning,
  PhLink,
  PhList,
  PhListBullets,
  PhLockKey,
  PhLockSimple,
  PhMagnifyingGlass,
  PhMailbox,
  PhMapPin,
  PhMapTrifold,
  PhMicrophoneStage,
  PhMicroscope,
  PhMicrophone,
  PhMinus,
  PhMusicNotes,
  PhMusicNotesSimple,
  PhNotePencil,
  PhPackage,
  PhPalette,
  PhPaperclip,
  PhPencilSimple,
  PhPianoKeys,
  PhPlant,
  PhPlus,
  PhProhibit,
  PhPuzzlePiece,
  PhQuestion,
  PhRecycle,
  PhRobot,
  PhRocket,
  PhRuler,
  PhScales,
  PhScroll,
  PhShieldCheck,
  PhShuffle,
  PhSparkle,
  PhSpeakerHigh,
  PhSquaresFour,
  PhStar,
  PhStarFour,
  PhStop,
  PhTagSimple,
  PhTarget,
  PhTent,
  PhTextAa,
  PhToolbox,
  PhTrash,
  PhTreeStructure,
  PhTrophy,
  PhUploadSimple,
  PhDownloadSimple,
  PhWarning,
  PhWaves,
  PhWrench,
  PhX,
  PhXCircle,
} from '@phosphor-icons/vue'

export const PHOSPHOR_MAP = {
  '☐': PhCheckSquare,
  '☑': PhCheckSquare,
  '☞': PhHandPointing,
  '☰': PhList,
  '♻️': PhRecycle,
  '⚖️': PhScales,
  '⚗️': PhFlask,
  '⚠️': PhWarning,
  '⚛️': PhAtom,
  '⚡': PhLightning,
  '⚙': PhGear,
  '⚙️': PhGear,
  '✅': PhCheckFat,
  '✅️': PhCheckFat,
  '✉️': PhEnvelope,
  '✏️': PhPencilSimple,
  '✓': PhCheck,
  '✔': PhCheckFat,
  '✕': PhX,
  '✎': PhPencilSimple,
  '✍️': PhPencilSimple,
  '✦': PhStarFour,
  '✨': PhSparkle,
  '❤️': PhHeart,
  '❌': PhXCircle,
  '❓': PhQuestion,
  '⭐': PhStar,
  '➕': PhPlus,
  '➖': PhMinus,
  '⬇️': PhArrowDown,
  '⬡': PhHexagon,
  '🌟': PhSparkle,
  '🌊': PhWaves,
  '🌍': PhGlobeHemisphereEast,
  '🌐': PhInfo,
  '🌳': PhTreeStructure,
  '🌾': PhPlant,
  '🎁': PhGift,
  '🎊': PhConfetti,
  '🎙️': PhMicrophoneStage,
  '🎤': PhMicrophone,
  '🎨': PhPalette,
  '🎯': PhTarget,
  '🎲': PhDiceFive,
  '🎵': PhMusicNotes,
  '🎶': PhMusicNotes,
  '🎼': PhMusicNotesSimple,
  '🎹': PhPianoKeys,
  '🏆': PhTrophy,
  '🏕️': PhTent,
  '🏗️': PhCraneTower,
  '🏘️': PhBuildings,
  '🏛️': PhBank,
  '🏠': PhHouse,
  '🏡': PhHouseSimple,
  '🏷️': PhTagSimple,
  '🏺': PhHourglassHigh,
  '👆': PhHandPointing,
  '👇': PhHandPointing,
  '👉': PhHandPointing,
  '💎': PhDiamond,
  '💡': PhLightbulb,
  '💫': PhSparkle,
  '💬': PhChatTeardrop,
  '💻': PhDesktop,
  '💾': PhFloppyDisk,
  '📁': PhFolder,
  '📂': PhFolderOpen,
  '📄': PhFile,
  '📅': PhCalendar,
  '📈': PhChartLineUp,
  '📉': PhChartLineDown,
  '📊': PhChartBar,
  '📋': PhClipboardText,
  '📍': PhMapPin,
  '📎': PhPaperclip,
  '📐': PhRuler,
  '📏': PhRuler,
  '📖': PhBookOpenText,
  '📗': PhBookOpen,
  '📚': PhListBullets,
  '📜': PhScroll,
  '📝': PhNotePencil,
  '📤': PhUploadSimple,
  '📥': PhDownloadSimple,
  '📦': PhPackage,
  '📭': PhMailbox,
  '🔀': PhShuffle,
  '🔍': PhMagnifyingGlass,
  '🔍️': PhMagnifyingGlass,
  '🔎': PhMagnifyingGlass,
  '🔊': PhSpeakerHigh,
  '🔒': PhLockSimple,
  '🔖': PhBookmarkSimple,
  '🔗': PhLink,
  '🔐': PhLockKey,
  '🔣': PhKeyboard,
  '🔤': PhTextAa,
  '🔧': PhWrench,
  '🔴': PhCircle,
  '🔵': PhCircle,
  '🔥': PhFire,
  '🔬': PhMicroscope,
  '🕸️': PhGraph,
  '🖼️': PhImage,
  '🗂️': PhFolders,
  '🗑️': PhTrash,
  '🗓️': PhCalendar,
  '🗣️': PhSpeakerHigh,
  '🗺': PhMapTrifold,
  '🗺️': PhMapTrifold,
  '🛠': PhWrench,
  '🛠️': PhWrench,
  '🛡️': PhShieldCheck,
  '🔄': PhArrowsClockwise,
  '🙌': PhHandsPraying,
  '🙏': PhHandsPraying,
  '🤖': PhRobot,
  '🟠': PhCircle,
  '🟡': PhCircle,
  '🟢': PhCircle,
  '🟣': PhCircle,
  '🚀': PhRocket,
  '🚪': PhDoor,
  '🚫': PhProhibit,
  '🧑‍💻': PhDesktop,
  '🧩': PhPuzzlePiece,
  '🧪': PhFlask,
  '🧬': PhDna,
  '🧭': PhCompass,
  '🧮': PhCalculator,
  '🧰': PhToolbox,
  '🥧': PhChartPie,
  '↔️': PhArrowsLeftRight,
  '↕️': PhArrowsDownUp,
  '⛶': PhArrowsOut,
  '⛷': PhArrowsIn,
  '⏹': PhStop,
  'ℹ️': PhInfo,
}

export function resolvePhosphorIcon(icon) {
  return PHOSPHOR_MAP[icon] || null
}
