import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

const testsDir = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(testsDir, '..')

function readSource(path) {
  return readFileSync(resolve(projectRoot, path), 'utf8')
}

describe('vocabulary explore page shell wiring', () => {
  it('registers /explore/vocabulary as a words peer route and layout page', () => {
    const exploreRoutes = readSource('src/main/router/exploreRoutes.js')

    expect(exploreRoutes).toContain("path: 'explore/vocabulary'")
    expect(exploreRoutes).toContain("redirect: (to) => ({")
    expect(exploreRoutes).toContain("'/explore/vocabulary/view'")
    expect(exploreRoutes).toContain("path: 'view'")
    expect(exploreRoutes).toContain("path: 'import'")
    expect(exploreRoutes).toContain("path: 'manage'")
    expect(readSource('src/main/App.vue')).toContain("normalizedPath.startsWith('/explore/vocabulary')")
    expect(readSource('src/main/router.js')).toContain("'/explore/vocabulary/view':")
  })

  it('exposes vocabulary page from words entry points and bars', () => {
    expect(readSource('src/main/views/menu/portals/WordsPage.vue')).toContain("'/explore/vocabulary/view'")
    expect(readSource('src/main/views/HomePage.vue')).toContain("navigateTo('/explore/vocabulary/view')")
    expect(readSource('src/main/config/BarAndTabs/ExploreBarConfig.js')).toContain("'/explore/vocabulary/view'")
    expect(readSource('src/main/config/BarAndTabs/SideBarConfig.js')).toContain("'/explore/vocabulary/view'")
  })

  it('keeps the explore words tab active across vocabulary subpages', () => {
    const exploreBar = readSource('src/main/config/BarAndTabs/ExploreBarConfig.js')

    expect(exploreBar).toContain("activeMatchPaths: [")
    expect(exploreBar).toContain("withRouteLocale(route, '/explore/vocabulary/view')")
    expect(exploreBar).toContain("withRouteLocale(route, '/explore/vocabulary/import')")
    expect(exploreBar).toContain("withRouteLocale(route, '/explore/vocabulary/manage')")
  })

  it('keeps the words parent entry on /menu/words while listing vocabulary before YuBao pages', () => {
    const wordsPortal = readSource('src/main/views/menu/portals/WordsPage.vue')
    const homePage = readSource('src/main/views/HomePage.vue')
    const exploreBar = readSource('src/main/config/BarAndTabs/ExploreBarConfig.js')
    const sidebar = readSource('src/main/config/BarAndTabs/SideBarConfig.js')
    const menuBar = readSource('src/main/config/BarAndTabs/MenuBarConfig.js')

    expect(exploreBar).toContain("defaultTo: { path: withRouteLocale(route, '/menu/words') }")
    expect(exploreBar).toContain("defaultChild: '/explore/vocabulary/view'")
    expect(menuBar).toContain("defaultTo: { path: withRouteLocale(route, '/menu/words') }")
    expect(sidebar).toContain("path: withRouteLocale(route, '/menu/words')")
    expect(sidebar).toContain("path: buildLocalePath('zh-Hant', '/explore/vocabulary/view')")

    expect(wordsPortal.indexOf('handleWordList')).toBeLessThan(wordsPortal.indexOf('handleYuBaoVocabulary'))
    expect(homePage.indexOf("navigateTo('/explore/vocabulary/view')")).toBeLessThan(homePage.indexOf("navigateTo('/explore/yubao?tab=vocabulary')"))
    expect(exploreBar.indexOf("'/explore/vocabulary/view'")).toBeLessThan(exploreBar.indexOf("'/explore/yubao?tab=vocabulary'"))
    expect(sidebar.indexOf("'/explore/vocabulary/view'")).toBeLessThan(sidebar.indexOf("'/explore/yubao?tab=vocabulary'"))
  })

  it('keeps the vocabulary shell focused on page-level navigation', () => {
    const vocabularyPage = readSource('src/main/views/explore/word/VocabularyPage.vue')
    const vocabularyScss = readSource('src/main/views/explore/word/vocabulary/vocabulary.scss')

    expect(vocabularyPage).toContain('<router-view')
    expect(vocabularyPage).toContain('page-tab-navigation')
    expect(vocabularyPage).toContain('page-tab-container')
    expect(vocabularyPage).toContain('page-tab-btn')
    expect(vocabularyPage).not.toContain('class="top-controls"')
    expect(vocabularyScss).toContain('.page-tab-navigation')
    expect(vocabularyScss).toContain('.page-tab-container')
    expect(vocabularyScss).toContain('&.active')
    expect(vocabularyPage).toContain("'/explore/vocabulary/view'")
    expect(vocabularyPage).toContain("'/explore/vocabulary/import'")
    expect(vocabularyPage).toContain("'/explore/vocabulary/manage'")
    expect(vocabularyPage).toContain('getVocabularyMe')
    expect(vocabularyPage).toContain('userStore')
    expect(vocabularyPage).toContain('if (!userStore.authReady)')
    expect(vocabularyPage).toContain('if (!userStore.isAuthenticated)')
    expect(vocabularyPage).toContain('watch(')
    expect(vocabularyPage).toContain('can_upload')
    expect(vocabularyPage).toContain('permission_level')
    expect(vocabularyPage).toContain('can_view_logs')
    expect(vocabularyPage).not.toContain('redirectUnavailablePage')
    expect(vocabularyPage).toContain("t('words.wordList.tabs.contribute')")
    expect(vocabularyPage).not.toContain("t('words.wordList.tabs.locations')")
    expect(vocabularyPage).not.toContain('getVocabularyItems')
    expect(vocabularyPage).not.toContain('uploadVocabulary')
    expect(vocabularyPage).not.toContain('getVocabularyLocations')
    expect(vocabularyPage).toContain('<ChoiceSelector')
    expect(vocabularyPage).toContain('isQueryTabActive')
    expect(vocabularyPage).toContain('contributeTabPaths')
    expect(vocabularyPage).toContain("'/explore/vocabulary/manage'")
  })

  it('keeps vocabulary card and map queries separate from the table API', () => {
    const vocabularyPage = readSource('src/main/views/explore/word/vocabulary/VocabularyViewPage.vue')
    const vocabularyScss = readSource('src/main/views/explore/word/vocabulary/vocabulary.scss')
    const topControls = readSource('src/main/views/explore/word/vocabulary/VocabularyTopControls.vue')

    expect(vocabularyPage).toContain("return viewMode.value === 'card'")
    expect(vocabularyPage).toContain("return viewMode.value === 'map'")
    expect(vocabularyPage).toContain('tab: nextMode,')
    expect(vocabularyPage).toContain('const canLoadMore = computed')
    expect(topControls).toContain('@media (max-aspect-ratio: 1 / 1)')
    expect(vocabularyScss).toContain('flex-wrap: wrap')
    expect(topControls).not.toContain('<ChoiceSelector')
    expect(vocabularyPage).not.toContain('{{ mode.icon }}')
    expect(vocabularyPage).toContain('getVocabularyItems(buildVocabularyItemsParams())')
    expect(vocabularyPage).toContain('getVocabularyMapPoints(buildVocabularyMapPointsParams())')
    expect(vocabularyPage).toContain('getVocabularyMapItems(buildVocabularyMapItemsParams())')
    expect(vocabularyPage).toContain('getVocabularyStandardWords(buildVocabularyStandardWordsParams())')
    expect(vocabularyPage).toContain('loadActiveViewMode()')
    expect(vocabularyPage).toContain('locations: selectedLocations.value')
    expect(vocabularyPage).toContain('standard_words: selectedStandardWords.value')
    expect(vocabularyPage).toContain('items: point.items || []')
    expect(vocabularyPage).toContain('search_fields: normalizeSelectedSearchFields()')
    expect(vocabularyPage).toContain('const selectedSearchFields = ref([])')
    expect(vocabularyPage).toContain('const selectedLocations = ref([])')
    expect(vocabularyPage).toContain('const selectedStandardWord = ref(\'\')')
    expect(vocabularyPage).toContain('const selectedStandardWords = computed')
    expect(vocabularyPage).toContain('const singleSelect = ref(true)')
    expect(vocabularyPage).toContain('const selectedStandardWordsModel = ref([])')
    expect(topControls).toContain('<SimpleSelectDropdown')
    expect(topControls).toContain('SwitchToggle')
    expect(vocabularyPage).toContain('loadVocabularyLocationOptions')
    expect(vocabularyPage).toContain('loadVocabularyStandardWords')
    expect(vocabularyPage).not.toContain('parseLocationFilter')
    expect(vocabularyPage).toContain('const mapPoints = ref([])')
    expect(vocabularyPage).toContain('mapDataForVocabularyMap')
    expect(vocabularyPage).toContain('handleMapPointClick')
    expect(vocabularyPage).toContain('normalizeMapPointLocations')
    expect(vocabularyPage).toContain('@marker-click="handleMapPointClick"')
    expect(vocabularyPage).toContain('shouldUseVocabularyMapItemsApi()')
    expect(vocabularyPage).toContain('isMapDetailModalOpen')
    expect(vocabularyPage).toContain('isLoadingMapDetail')
    expect(vocabularyPage).toContain('mapDetailEntries')
    expect(vocabularyPage).toContain('mapDetailError')
    expect(vocabularyPage).toContain('selectedMapPointLabel')
    expect(vocabularyPage).not.toContain('map-side-panel')
    expect(vocabularyPage).not.toContain('map-result-list')
    expect(vocabularyPage).toContain('locations,')
    expect(vocabularyPage).toContain('location_label')
    expect(vocabularyPage).toContain('standard_word')
    expect(vocabularyPage).toContain('local_expression')
    expect(vocabularyPage).toContain('ipa')
    expect(vocabularyPage).toContain('notes')
    expect(vocabularyPage).toContain("value: 'pronunciation'")
    expect(vocabularyPage).toContain("value: 'detail'")
    expect(vocabularyPage).not.toContain("value: 'ipa'")
    expect(vocabularyPage).not.toContain("value: 'notes'")
    expect(vocabularyPage).not.toContain('const mappableEntries = computed')
    expect(vocabularyPage).toContain('db-key="vocabulary"')
    expect(vocabularyPage).toContain('table-name="vocabulary_entries"')
    expect(vocabularyPage).toContain('api-adapter="vocabulary"')
    expect(vocabularyPage).toContain('primary-key="id"')
    expect(vocabularyPage).not.toContain(':can-edit="canUseVocabularyTable"')
    expect(vocabularyPage).not.toContain('const canUseVocabularyTable = computed')
    expect(vocabularyPage).not.toContain("mode.key !== 'table'")
    expect(vocabularyPage).not.toContain('uploadVocabulary')
    expect(vocabularyPage).not.toContain('getVocabularyLocations')
    expect(vocabularyPage).not.toContain('sortBy')
    expect(vocabularyPage).not.toContain('sortOptions')
    expect(vocabularyPage).not.toContain('previewEntries')
  })

  it('feeds VocabularyMap drawable aggregate points and a fixed-height canvas', () => {
    const vocabularyPage = readSource('src/main/views/explore/word/vocabulary/VocabularyViewPage.vue')
    const vocabularyMap = readSource('src/main/components/map/VocabularyMap.vue')
    const vocabularyScss = readSource('src/main/views/explore/word/vocabulary/vocabulary.scss')

    expect(vocabularyPage).toContain('<VocabularyMap')
    expect(vocabularyPage).toContain("import VocabularyMap from '@/main/components/map/VocabularyMap.vue'")
    expect(vocabularyPage).not.toContain('<YuBaoMap')
    expect(vocabularyPage).not.toContain("import YuBaoMap from '@/main/components/map/YuBaoMap.vue'")
    expect(vocabularyMap).toContain('name: "VocabularyMap"')
    expect(vocabularyMap).toContain("const displayMode = defineModel('displayMode', { default: 'overview' })")
    expect(vocabularyMap).toContain("value: 'overview', label: t('map.vocabularyMap.controls.overview')")
    expect(vocabularyMap).toContain("value: 'location', label: t('map.vocabularyMap.controls.location')")
    expect(vocabularyMap).toContain("value: 'pronunciation', label: t('map.vocabularyMap.controls.pronunciation')")
    expect(vocabularyMap).toContain("value: 'definition', label: t('map.vocabularyMap.controls.definition')")
    expect(vocabularyMap).not.toContain("label: '概覽'")
    expect(vocabularyMap).not.toContain("label: '語音'")
    expect(vocabularyMap).toContain('canShowDetailModes.value')
    expect(vocabularyMap).toContain('return canShowDetailModes.value ? detailDisplayModeOptions.value : overviewDisplayModeOptions.value')
    expect(vocabularyMap).toContain("displayMode.value = 'overview'")
    expect(vocabularyMap).toContain('watch(displayModeOptions')
    expect(vocabularyPage).toContain("mapDisplayMode.value = 'overview'")
    expect(vocabularyMap).toContain("if (displayMode.value === 'overview')")
    expect(vocabularyMap).toContain('text = item.entryCount ? String(item.entryCount) :')
    expect(vocabularyMap).toContain('item.localExpression')
    expect(vocabularyPage).toContain('pronunciation: point.pronunciation || point.markerLabel')
    expect(vocabularyPage).toContain('entryCount: point.entryCount')
    expect(vocabularyPage).toContain('markerLabel: entryCount ? String(entryCount) : (locationLabel || locationName)')
    expect(vocabularyScss).toContain('height: 69dvh')
    expect(vocabularyScss).toContain('max-height: 69dvh')
  })

  it('uses dedicated vocabulary locations APIs for location metadata management', () => {
    const vocabularyPage = readSource('src/main/views/explore/word/vocabulary/VocabularyManagePage.vue')

    expect(vocabularyPage).toContain('getVocabularyLocations')
    expect(vocabularyPage).toContain('updateVocabularyLocation')
    expect(vocabularyPage).toContain('loadVocabularyLocations')
    expect(vocabularyPage).toContain('locationFilters')
    expect(vocabularyPage).toContain('locationPagination')
    expect(vocabularyPage).toContain('buildLocationQueryParams')
    expect(vocabularyPage).toContain('applyLocationFilters')
    expect(vocabularyPage).toContain('resetLocationFilters')
    expect(vocabularyPage).toContain('goToLocationPage')
    expect(vocabularyPage).toContain('const params = buildLocationQueryParams()')
    expect(vocabularyPage).toContain('getVocabularyLocations(params)')
    expect(vocabularyPage).toContain("t('words.wordList.locations.filters.locationName')")
    expect(vocabularyPage).toContain("t('words.wordList.locations.filters.userId')")
    expect(vocabularyPage).toContain('words.wordList.pagination.total')
    expect(vocabularyPage).toContain('handleSaveLocation')
    expect(vocabularyPage).toContain('<AppModal')
    expect(vocabularyPage).toContain('editingLocationDraft')
    expect(vocabularyPage).toContain('openLocationEditor')
    expect(vocabularyPage).toContain('closeLocationEditor')
    expect(vocabularyPage).toContain('handleSaveEditingLocation')
    expect(vocabularyPage).not.toContain('v-model="location[field.key]"')
    expect(vocabularyPage).not.toContain("activeWorkflow === 'locations'")
    expect(vocabularyPage).toContain("t('words.wordList.locations.title')")
    expect(vocabularyPage).not.toContain('reviewSubmissions')
    expect(vocabularyPage).not.toContain("t('words.wordList.review.approve')")
  })

  it('includes operation log querying inside the vocabulary manage page', () => {
    const vocabularyPage = readSource('src/main/views/explore/word/vocabulary/VocabularyManagePage.vue')

    expect(vocabularyPage).toContain('getVocabularyLogs')
    expect(vocabularyPage).toContain('loadVocabularyLogs')
    expect(vocabularyPage).toContain('getVocabularyMe')
    expect(vocabularyPage).toContain('can_view_logs')
    expect(vocabularyPage).toContain('<section v-if="shouldShowAccessGate" class="content-area">')
    expect(vocabularyPage).toContain('manageSection === \'logs\' && canViewVocabularyLogs')
    expect(vocabularyPage).toContain('if (canViewVocabularyLogs.value)')
    expect(vocabularyPage).toContain('logRows')
    expect(vocabularyPage).toContain('normalizeVocabularyLog')
    expect(vocabularyPage).toContain('parseLogPayload')
    expect(vocabularyPage).toContain('buildLogPayloadSummary')
    expect(vocabularyPage).toContain('payload_json')
    expect(vocabularyPage).toContain('rollback_supported')
    expect(vocabularyPage).toContain("t('words.wordList.logs.rollbackSupported')")
    expect(vocabularyPage).toContain("t('words.wordList.logs.rollbackUnsupported')")
    expect(vocabularyPage).toContain('words.wordList.logs.payload.deletedEntries')
    expect(vocabularyPage).toContain('words.wordList.logs.payload.changedFields')
    expect(vocabularyPage).toContain("t('words.wordList.logs.title')")
    expect(vocabularyPage).toContain("t('words.wordList.logs.refresh')")
    expect(vocabularyPage).toContain('logFilters')
    expect(vocabularyPage).toContain('logPagination')
    expect(vocabularyPage).toContain('logFilterFields')
    expect(vocabularyPage).toContain('buildLogQueryParams')
    expect(vocabularyPage).toContain('applyLogFilters')
    expect(vocabularyPage).toContain('resetLogFilters')
    expect(vocabularyPage).toContain('goToLogPage')
    expect(vocabularyPage).toContain('const params = buildLogQueryParams()')
    expect(vocabularyPage).toContain('getVocabularyLogs(params)')
    expect(vocabularyPage).toContain('logs-filter-grid')
    expect(vocabularyPage).toContain('v-model="logFilters')
    expect(vocabularyPage).toContain('words.wordList.pagination.total')
    expect(vocabularyPage).not.toContain('rollbackVocabulary')
    expect(vocabularyPage).toContain('<RadioGroup')
    expect(vocabularyPage).toContain("name=\"manage-section\"")
    expect(vocabularyPage).toContain("const manageSection = ref('entries')")
    expect(vocabularyPage).not.toContain("t('words.wordList.logs.rollbackAction')")
  })

  it('keeps vocabulary design tokens and copy independent from YuBao internals', () => {
    const viewPage = readSource('src/main/views/explore/word/vocabulary/VocabularyViewPage.vue')
    const importPage = readSource('src/main/views/explore/word/vocabulary/VocabularyImportPage.vue')
    const managePage = readSource('src/main/views/explore/word/vocabulary/VocabularyManagePage.vue')
    const vocabularyMap = readSource('src/main/components/map/VocabularyMap.vue')
    const vocabularyScss = readSource('src/main/views/explore/word/vocabulary/vocabulary.scss')

    expect(viewPage).not.toContain('words.yuBaoPage.states')
    expect(managePage).not.toContain('words.yuBaoPage.states')
    expect(viewPage).toContain('words.wordList.states.loadingCards')
    expect(viewPage).toContain(':close-label="t(\'common.button.close\')"')

    expect(importPage).not.toContain('使用音典数据')
    expect(importPage).not.toContain('点击地图获取经纬度')
    expect(importPage).not.toContain('未找到音典数据')
    expect(importPage).not.toContain('已填入音典数据')
    expect(importPage).not.toContain('获取音典数据失败')
    expect(importPage).toContain("t('words.wordList.upload.useYindianData')")
    expect(importPage).toContain("t('words.wordList.upload.mapPickerHint')")

    expect(vocabularyMap).not.toContain('yubao-')
    expect(vocabularyMap).not.toContain('map.yuBaoMap')
    expect(vocabularyMap).toContain('vocabulary-markers')
    expect(vocabularyMap).toContain("t('map.vocabularyMap.loading.mapData')")
    expect(vocabularyMap).not.toContain('🎯')
    expect(vocabularyMap).not.toContain('⛶')
    expect(vocabularyMap).not.toContain('✕')

    expect(vocabularyScss).not.toContain('!important')
    expect(vocabularyScss).toContain('max-width: 1200px')
    expect(vocabularyScss).toContain('margin: 0 auto')
    expect(vocabularyScss).not.toContain('position: sticky;\n  top: 0;\n  z-index: 20;\n  display: flex;\n  flex-wrap: nowrap')
    expect(vocabularyScss).toContain('min-height: 300px')
  })

  it('keeps vocabulary import flow isolated from view and manage pages', () => {
    const importPage = readSource('src/main/views/explore/word/vocabulary/VocabularyImportPage.vue')
    const viewPage = readSource('src/main/views/explore/word/vocabulary/VocabularyViewPage.vue')
    const managePage = readSource('src/main/views/explore/word/vocabulary/VocabularyManagePage.vue')

    expect(importPage).toContain('uploadVocabulary')
    expect(importPage).toContain('backendPreview')
    expect(importPage).toContain('handlePreviewImport')
    expect(importPage).toContain('handleImportAfterPreview')
    expect(importPage).toContain('would_delete_existing_count')
    expect(importPage).toContain('shouldConfirmOverwrite')
    expect(importPage).toContain('isOverwriteConfirmed')
    expect(importPage).toContain("t('words.wordList.upload.confirmOverwrite')")
    expect(importPage).toContain('overwrite: shouldConfirmOverwrite.value ? isOverwriteConfirmed.value : false')
    expect(importPage).toContain("parser_mode: uploadParserMode.value")
    expect(importPage).toContain('isVocabularyPreviewFile(file)')
    expect(importPage).toContain('isVocabularyUploadFile(file)')
    expect(importPage).toContain('uploadFile.value || importFlow.pendingFile.value')
    expect(importPage).toContain("accept=\".xlsx,.xls,.csv,.tsv,.docx,.doc\"")
    expect(importPage).toContain(':mapping-enabled="isVocabularyPreviewFile(importFlow.pendingFile.value)"')
    expect(importPage).toContain('v-if="importFlow.pendingFile.value"')
    expect(importPage).toContain(':model-value="Boolean(importFlow.pendingFile.value)"')
    expect(importPage).toContain('@reset="importFlow.clearPreview"')
    expect(importPage).toContain('style="display: none"')
    expect(importPage).toContain('canConfirmUpload')
    expect(importPage).toContain('requiresLogin')
    expect(importPage).toContain('requiresVocabularyPermission')
    expect(importPage).toContain('uploadAccessNotice')
    expect(importPage).toContain("t('words.wordList.access.loginUploadDesc')")
    expect(importPage).not.toContain('navigateToAuth()')
    expect(importPage).toContain("t('words.wordList.upload.submit')")
    expect(importPage).toContain("t('words.wordList.upload.unsupportedFile')")
    expect(viewPage).not.toContain('uploadVocabulary')
    expect(managePage).not.toContain('uploadVocabulary')
    expect(importPage).toContain('<RadioGroup')
    expect(importPage).toContain("t('words.wordList.upload.enterLocationInfo')")
    expect(importPage).toContain("t('words.wordList.upload.chooseFile')")
    expect(importPage).toContain('upload-section-title')
  })

  it('gates vocabulary protected pages with localized login and permission prompts', () => {
    const vocabularyPage = readSource('src/main/views/explore/word/VocabularyPage.vue')
    const importPage = readSource('src/main/views/explore/word/vocabulary/VocabularyImportPage.vue')
    const managePage = readSource('src/main/views/explore/word/vocabulary/VocabularyManagePage.vue')
    const vocabularyScss = readSource('src/main/views/explore/word/vocabulary/vocabulary.scss')
    const zhHantWords = JSON.parse(readSource('src/i18n/locales/zh-Hant/words.json'))
    const zhCnWords = JSON.parse(readSource('src/i18n/locales/zh-CN/words.json'))
    const enWords = JSON.parse(readSource('src/i18n/locales/en/words.json'))

    expect(vocabularyPage).toContain(':is-authenticated="isAuthenticated"')
    expect(vocabularyPage).toContain(':is-auth-ready="isAuthReady"')
    expect(importPage).not.toContain('v-if="shouldShowAccessGate"')
    expect(importPage).toContain('v-if="requiresLogin"')
    expect(importPage).toContain('{{ uploadAccessNotice }}')
    expect(importPage).toContain('navigateToSuggestion')
    expect(importPage).toContain("t('words.wordList.access.requestEditPermission')")
    expect(importPage).toContain("'/menu/about/suggestion'")
    expect(managePage).toContain('v-if="shouldShowAccessGate"')
    expect(importPage).not.toContain('access-gate-actions')
    expect(managePage).toContain("t('words.wordList.access.loginManageTitle')")
    expect(managePage).toContain("t('words.wordList.access.noManagePermissionTitle')")
    expect(managePage).toContain("t('words.wordList.access.backToList')")
    expect(managePage).toContain('if (hasVocabularyPermission.value)')
    expect(managePage).toContain('if (canViewVocabularyLogs.value)')
    expect(vocabularyScss).toContain('.access-gate')
    expect(vocabularyScss).toContain('.access-gate-actions')

    for (const words of [zhHantWords, zhCnWords, enWords]) {
      expect(words.wordList.access.loginUploadTitle).toBeTruthy()
      expect(words.wordList.access.loginManageTitle).toBeTruthy()
      expect(words.wordList.access.noUploadPermissionTitle).toBeTruthy()
      expect(words.wordList.access.noManagePermissionTitle).toBeTruthy()
      expect(words.wordList.access.loginAction).toBeTruthy()
      expect(words.wordList.access.backToList).toBeTruthy()
    }
  })

  it('matches the YuBao card grid density and glass card treatment', () => {
    const vocabularyScss = readSource('src/main/views/explore/word/vocabulary/vocabulary.scss')

    expect(vocabularyScss).toContain('grid-template-columns: repeat(auto-fill, minmax(250px, 1fr))')
    expect(vocabularyScss).toContain('background: var(--glass-80)')
    expect(vocabularyScss).toContain('border: 0.5px solid var(--glass-90)')
    expect(vocabularyScss).toContain('transform: translateY(-2px)')
    expect(vocabularyScss).toContain('font-family: var(--font-monospace')
  })

  it('adapts UniversalTable permissions and vocabulary batch replace payloads for vocabulary SQL', () => {
    const universalTable = readSource('src/main/components/TableAndTree/UniversalTable.vue')
    const vocabularyApi = readSource('src/api/main/vocabulary.js')

    expect(universalTable).toContain('canEdit: { type: Boolean, default: false }')
    expect(universalTable).toContain('const canUseTableActions = computed')
    expect(universalTable).toContain("props.apiAdapter === 'vocabulary'")
    expect(universalTable).toContain('v-if="canUseTableActions"')
    expect(universalTable).toContain('search_columns: props.columns.map(c => c.key)')
    expect(vocabularyApi).toContain('stripVocabularyBatchReplaceParams')
    expect(vocabularyApi).toContain('delete rest.pk_column')
  })
})
